name: Deploy Site

on:
    push:
        branches: doc-pages

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Prepare pnpm
              uses: pnpm/action-setup@v4
            - name: Prepare Node.js 22
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - name: Install dependencies
              run: pnpm install
            - name: Generate site
              run: pnpm docs:build
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh_pages
                publish_dir: ./docs/.vitepress/dist
                cname: doc.huanhq.com